=== Assumeru/Imperator4J/src/main/webapp/WEB-INF/maps/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xs:complexType name="argument">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="type"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:element name="map">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="name"/>
				<xs:element name="players">
					<xs:simpleType>
						<xs:restriction base="xs:positiveInteger">
							<xs:minInclusive value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="description" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute ref="xml:lang" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="territories">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="territory" maxOccurs="unbounded" minOccurs="2">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name"/>
										<xs:element name="borders">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="border" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="regions" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="region" maxOccurs="unbounded" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="regions" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="region" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name"/>
										<xs:element type="xs:integer" name="units"/>
									</xs:sequence>
									<xs:attribute type="xs:string" name="id" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="missions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mission" maxOccurs="unbounded">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="argument" minOccurs="0" maxOccurs="unbounded" type="argument" />
										<xs:element type="xs:string" name="name" minOccurs="0"/>
										<xs:element type="xs:string" name="description" minOccurs="0"/>
										<xs:element name="conditions" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="condition" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="argument" minOccurs="0" maxOccurs="unbounded" type="argument" />
															</xs:sequence>
															<xs:attribute type="xs:string" name="class" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:integer" name="missionId" use="required"/>
									<xs:attribute name="availability" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute type="xs:string" name="class" use="optional"/>
									<xs:attribute type="xs:integer" name="fallback" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:integer" name="id" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Assumeru/Imperator4J/src/main/webapp/WEB-INF/maps/0.xml
<?xml version="1.0" encoding="UTF-8"?>
<map id="0" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
	<name>Benelux</name>
	<players>2</players>
	<description xml:lang="en-US"><![CDATA[
		<p>The Benelux is an economic union between the European nations of <strong>Be</strong>lgium, the <strong>Ne</strong>therlands, and <strong>Lux</strong>embourg.</p>
		<p>This map is made up of the provinces of Belgium and the Netherlands in addition to the Brussels-Capital region and the Grand Duchy of Luxembourg.</p>
		<p>In order to win, one needs to conquer all 24 of these territories, thereby eliminating the other player.</p>
	]]></description>
	<description xml:lang="de-DE"><![CDATA[
		<p>Der Benelux ist eine Union die aus <strong>Be</strong>lgien, den Niederlanden (<strong>Ne</strong>derland) und <strong>Lu</strong>xemburg besteht.</p>
		<p>Dieser Karte besteht auf den belgischen und niederländischen Provinzen zusammen mit der Region Brüssel-Hauptstadt und das Großherzogtum Luxemburg.</p>
		<p>Um zu gewinnen muss man alle 24 gebieten erobern und damit die andere Spieler eliminiert.</p>
	]]></description>
	<description xml:lang="fr-FR"><![CDATA[
		<p>Le Benelux est une union économique entre la <strong>Be</strong>lgique, les Pays-Bas (<strong>Ne</strong>derland) et le <strong>Lu</strong>xembourg.</p>
		<p>Cette carte est composée des provinces de Belgique et de Pays-Bas en plus de la région de Bruxelles-Capitale et le Grand-Duché de Luxembourg.</p>
		<p>Pour gagner, il faut conquérir les 24 territoires, éliminant ainsi l'autre joueur.</p>
	]]></description>
	<description xml:lang="nl-NL"><![CDATA[
		<p>De Benelux is een economische unie tussen <strong>Be</strong>lgië, <strong>Ne</strong>derland en <strong>Lu</strong>xemburg.</p>
		<p>Deze kaart bestaat uit de provincies van België en Nederland, plus het Brussels Hoofdstedelijk gewest en het Groothertogdom Luxemburg.</p>
		<p>Om te winnen moet men alle 24 gebieden veroveren en daardoor de andere speler uitschakelen.</p>
	]]></description>
	<territories>
		<territory id="eu_be_antwerp">
			<name>Antwerp</name>
			<borders>
				<border>eu_be_eastflanders</border>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_limburg</border>
				<border>eu_nl_northbrabant</border>
				<border>eu_nl_zeeland</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_brussels">
			<name>Brussels</name>
			<borders>
				<border>eu_be_flemishbrabant</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_eastflanders">
			<name>East Flanders</name>
			<borders>
				<border>eu_be_antwerp</border>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_hainaut</border>
				<border>eu_be_westflanders</border>
				<border>eu_nl_zeeland</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_flemishbrabant">
			<name>Flemish Brabant</name>
			<borders>
				<border>eu_be_antwerp</border>
				<border>eu_be_brussels</border>
				<border>eu_be_eastflanders</border>
				<border>eu_be_hainaut</border>
				<border>eu_be_liege</border>
				<border>eu_be_limburg</border>
				<border>eu_be_walloonbrabant</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_hainaut">
			<name>Hainaut</name>
			<borders>
				<border>eu_be_eastflanders</border>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_namur</border>
				<border>eu_be_walloonbrabant</border>
				<border>eu_be_westflanders</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_liege">
			<name>Liege</name>
			<borders>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_limburg</border>
				<border>eu_be_luxembourg</border>
				<border>eu_be_namur</border>
				<border>eu_be_walloonbrabant</border>
				<border>eu_luxembourg</border>
				<border>eu_nl_limburg</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_limburg">
			<name>Limburg</name>
			<borders>
				<border>eu_be_antwerp</border>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_liege</border>
				<border>eu_nl_limburg</border>
				<border>eu_nl_northbrabant</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_luxembourg">
			<name>Luxembourg</name>
			<borders>
				<border>eu_be_liege</border>
				<border>eu_be_namur</border>
				<border>eu_luxembourg</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_namur">
			<name>Namur</name>
			<borders>
				<border>eu_be_hainaut</border>
				<border>eu_be_liege</border>
				<border>eu_be_luxembourg</border>
				<border>eu_be_walloonbrabant</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_westflanders">
			<name>West Flanders</name>
			<borders>
				<border>eu_be_eastflanders</border>
				<border>eu_be_hainaut</border>
				<border>eu_nl_zeeland</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_be_walloonbrabant">
			<name>Walloon Brabant</name>
			<borders>
				<border>eu_be_flemishbrabant</border>
				<border>eu_be_hainaut</border>
				<border>eu_be_liege</border>
				<border>eu_be_namur</border>
			</borders>
			<regions>
				<region>eu_belgium</region>
			</regions>
		</territory>
		<territory id="eu_luxembourg">
			<name>Grand Duchy of Luxembourg</name>
			<borders>
				<border>eu_be_liege</border>
				<border>eu_be_luxembourg</border>
			</borders>
		</territory>
		<territory id="eu_nl_drenthe">
			<name>Drenthe</name>
			<borders>
				<border>eu_nl_friesland</border>
				<border>eu_nl_groningen</border>
				<border>eu_nl_overijssel</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_flevoland">
			<name>Flevoland</name>
			<borders>
				<border>eu_nl_friesland</border>
				<border>eu_nl_gelderland</border>
				<border>eu_nl_northholland</border>
				<border>eu_nl_overijssel</border>
				<border>eu_nl_utrecht</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_friesland">
			<name>Friesland</name>
			<borders>
				<border>eu_nl_drenthe</border>
				<border>eu_nl_flevoland</border>
				<border>eu_nl_groningen</border>
				<border>eu_nl_northholland</border>
				<border>eu_nl_overijssel</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_gelderland">
			<name>Gelderland</name>
			<borders>
				<border>eu_nl_flevoland</border>
				<border>eu_nl_limburg</border>
				<border>eu_nl_northbrabant</border>
				<border>eu_nl_overijssel</border>
				<border>eu_nl_southholland</border>
				<border>eu_nl_utrecht</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_groningen">
			<name>Groningen</name>
			<borders>
				<border>eu_nl_drenthe</border>
				<border>eu_nl_friesland</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_limburg">
			<name>Limburg</name>
			<borders>
				<border>eu_be_liege</border>
				<border>eu_be_limburg</border>
				<border>eu_nl_gelderland</border>
				<border>eu_nl_northbrabant</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_northbrabant">
			<name>North Brabant</name>
			<borders>
				<border>eu_be_antwerp</border>
				<border>eu_be_limburg</border>
				<border>eu_nl_gelderland</border>
				<border>eu_nl_limburg</border>
				<border>eu_nl_southholland</border>
				<border>eu_nl_zeeland</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_northholland">
			<name>North Holland</name>
			<borders>
				<border>eu_nl_flevoland</border>
				<border>eu_nl_friesland</border>
				<border>eu_nl_southholland</border>
				<border>eu_nl_utrecht</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_overijssel">
			<name>Overijssel</name>
			<borders>
				<border>eu_nl_drenthe</border>
				<border>eu_nl_flevoland</border>
				<border>eu_nl_friesland</border>
				<border>eu_nl_gelderland</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_southholland">
			<name>South Holland</name>
			<borders>
				<border>eu_nl_gelderland</border>
				<border>eu_nl_northbrabant</border>
				<border>eu_nl_northholland</border>
				<border>eu_nl_utrecht</border>
				<border>eu_nl_zeeland</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_utrecht">
			<name>Utrecht</name>
			<borders>
				<border>eu_nl_flevoland</border>
				<border>eu_nl_gelderland</border>
				<border>eu_nl_northholland</border>
				<border>eu_nl_southholland</border>
			</borders>
			<regions>
				<region>eu_netherlands</region>
			</regions>
		</territory>
		<territory id="eu_nl_zeeland">
			<name>Zeeland</name>
			<borders>
				<border>eu_be_antwerp</border>
